"""add Department

Revision ID: 802b835ce19f
Revises: 7fa29e4fcde7
Create Date: 2025-04-15 22:29:12.113497

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '802b835ce19f'
down_revision = '7fa29e4fcde7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('department',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('address', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('department')
    # ### end Alembic commands ###
